name             'nsd'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures nsd'
long_description 'Installs/Configures nsd'
version          '0.1.0'
depends          'nsd_resource'
